# Generated by Django 5.2.17 on 2026-10-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_adminjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بازدید مجازی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='شناسه URL')),
                ('storage_dir', models.CharField(max_length=255, verbose_name='پوشه ذخیره\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازدید مجازی',
                'verbose_name_plural': 'بازدیدهای مجازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='listings.virtualtour', verbose_name='بازدید مجازی'),
        ),
    ]
