# Generated by Django 5.2.17 on 2026-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_virtualtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='تعداد بازدید'),
        ),
    ]
