# Generated by Django 5.2.17 on 2026-10-06 13:37

from django.db import migrations, models

from listings.parsing import parse_area, parse_bedrooms, parse_price


def backfill_numbers(apps, schema_editor):
    Property = apps.get_model("listings", "Property")
    for item in Property.objects.all():
        Property.objects.filter(pk=item.pk).update(
            price_value=parse_price(item.price_text),
            area_value=parse_area(item.specs),
            bedrooms=parse_bedrooms(item.specs),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_value',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='متراژ'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد خواب'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_value',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='قیمت (تومان)'),
        ),
        migrations.RunPython(backfill_numbers, migrations.RunPython.noop),
    ]
