# Generated by Django 5.2.17 on 2026-10-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=255)),
                ('source', models.CharField(db_index=True, max_length=120, verbose_name='منبع')),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('visitor_id', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='pin_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='خالی = عادی. ملک\u200cهای دارای عدد، به ترتیب اول صفحه اصلی نمایش داده می\u200cشوند.', null=True, verbose_name='ترتیب در ابتدای صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='properties/thumbs/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PropertyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'بازدید ملک'), ('whatsapp', 'کلیک واتساپ')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.property')),
            ],
            options={
                'verbose_name': 'رویداد ملک',
                'verbose_name_plural': 'رویدادهای ملک',
                'ordering': ['-created_at'],
            },
        ),
    ]
